export const ROMANIAN_BANKS: Record<string, string> = {
  RNCB: 'BCR (Banca Comercială Română)',
  BTRL: 'Banca Transilvania',
  INGB: 'ING Bank',
  BRDE: 'BRD – Groupe Société Générale',
  CECB: 'CEC Bank',
  TREZ: 'Trezoreria Statului',
  PIRB: 'First Bank',
  BREL: 'Libra Internet Bank',
  OTPV: 'OTP Bank România',
  BACX: 'UniCredit Bank',
  RZBR: 'Raiffeisen Bank',
  MIRO: 'Mihai Eminescu Banca',
  UGBI: 'Garanti BBVA',
  CARP: 'Patria Bank',
  EXIM: 'Eximbank',
  WBAN: 'WB Banca (fosta Idea Bank)',
}

export const ROMANIAN_BANKS_SWIFT: Record<string, string> = {
  RNCB: 'RNCBROBU',
  BTRL: 'BTRLRO22',
  BRDE: 'BRDEROBUXXX',
  INGB: 'INGBROBUXXX',
  RZBR: 'RZBRROBU',
  CECB: 'CECBROBU',
  BACX: 'BACXROBU',
  OTPV: 'OTPVROBU',
  PIRB: 'PIRBROBUXXX',
  BREL: 'BRELROBU',
  EXIM: 'EXIMROBUXXX',
  REVO: 'REVOROBU',
  WIPE: 'TRWIGB2L',
  TRWI: 'TRWIGB2L',
  UGBI: 'UGBIROBUXXX',
  BUCU: 'BUCUROBUXXX',
  CARP: 'CARPRO22',
  FNNB: 'FNNBROBUXXX',
  PRME: 'PRMEROBU',
  TREZ: 'TREZROBU',
  BNRB: 'BNRBROBUXXX',
  SALT: 'SALTROBU',
  IDEA: 'SALTROBU',
  MIND: 'MINDROBU',
}
